# Generated by Django 2.1.4 on 2018-12-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpost',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
